#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Bit-Vector
Version  : 7.4
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/S/ST/STBEY/Bit-Vector-7.4.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/ST/STBEY/Bit-Vector-7.4.tar.gz
Summary  : ~
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Bit-Vector-lib = %{version}-%{release}
Requires: perl-Bit-Vector-license = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Carp::Clan)

%description
=====================================
Package "Bit::Vector" Version 7.4
=====================================

%package dev
Summary: dev components for the perl-Bit-Vector package.
Group: Development
Requires: perl-Bit-Vector-lib = %{version}-%{release}
Provides: perl-Bit-Vector-devel = %{version}-%{release}
Requires: perl-Bit-Vector = %{version}-%{release}

%description dev
dev components for the perl-Bit-Vector package.


%package lib
Summary: lib components for the perl-Bit-Vector package.
Group: Libraries
Requires: perl-Bit-Vector-license = %{version}-%{release}

%description lib
lib components for the perl-Bit-Vector package.


%package license
Summary: license components for the perl-Bit-Vector package.
Group: Default

%description license
license components for the perl-Bit-Vector package.


%prep
%setup -q -n Bit-Vector-7.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Bit-Vector
cp Artistic.txt %{buildroot}/usr/share/package-licenses/perl-Bit-Vector/Artistic.txt
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/Bit/Vector.pm
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/Bit/Vector.pod
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/Bit/Vector/Overload.pm
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/Bit/Vector/Overload.pod
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/Bit/Vector/String.pm
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/Bit/Vector/String.pod

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Bit::Vector.3
/usr/share/man/man3/Bit::Vector::Overload.3
/usr/share/man/man3/Bit::Vector::String.3

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/auto/Bit/Vector/Vector.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Bit-Vector/Artistic.txt
